"""Initial schema from SQLite

Revision ID: 21de19ba224a
Revises: 
Create Date: 2025-11-09 12:33:09.623087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21de19ba224a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gyms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('club_name', sa.Text(), nullable=False),
    sa.Column('club_address', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_name')
    )
    op.create_table('sync_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('gyms_fetched', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('triggered_by', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_history_started_at', 'sync_history', ['started_at'], unique=False)
    op.create_table('capacity_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('users_count', sa.Integer(), nullable=False),
    sa.Column('users_limit', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_capacity_logs_gym_id', 'capacity_logs', ['gym_id'], unique=False)
    op.create_index('idx_capacity_logs_timestamp', 'capacity_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_capacity_logs_timestamp', table_name='capacity_logs')
    op.drop_index('idx_capacity_logs_gym_id', table_name='capacity_logs')
    op.drop_table('capacity_logs')
    op.drop_index('idx_sync_history_started_at', table_name='sync_history')
    op.drop_table('sync_history')
    op.drop_table('gyms')
    op.drop_table('credentials')
    # ### end Alembic commands ###
